#include "tokens.h"


char const * rlc_tok_result_message(RlcTokResult result)
{
	static char const * messages[] = {
		"tokenising successful",
		"end of source file reached",
		"invalid hexadecimal digit",
		"invalid octal digit.",
		"invalid decimal digit.",
		"invalid floating type specifier",
		"unclosed caracter/string literal.",
		"invalid hexadecimal escape sequence.",
		"invalid octal escape sequence.",
		"invalid decimal escape sequence.",
		"invalid escape sequence.",
		"invalid UTF-8 byte.",
		"empty character literal.",
		"unexpected symbol."
	};

	return messages[result];
}

char const * rlc_token_type_name(RlcTokenType type)
{
	static char const * const names[] = {
		"whitespace",
		"identifier",
		"hexadecimal number",
		"decimal number",
		"octal number",
		"character number",
		"UTF-8 character number",
		"UTF-16 character number",
		"UTF-32 character number",
		"0",
		"string",
		"UTF-8 string",
		"UTF-16 LE string",
		"UTF-16 BE string",
		"UTF-32 LE string",
		"UTF-32 BE string",

		"binary16 number",
		"binary32 number",
		"binary64 number",
		"binary128 number",

		"backslash",
		"comma",
		"dot",
		"three dot",
		"plus",
		"plus equal",
		"double plus",
		"double minus",
		"minus",
		"minus equal",
		"arrow",
		"asterisk",
		"asterisk equal",
		"double and",
		"and",
		"and equal",
		"double pipe",
		"pipe",
		"pipe equal",
		"greater",
		"greater equal",
		"LESS",
		"LESS_EQUAL",
		"ASSIGN",
		"EQUAL",
		"NOT_EQUAL",
		"DIVIDE",
		"DIVIDE_ASSIGN",
		"MODULO",
		"MODULO_ASSIGN",
		"SEMICOLON",
		"COLON",
		"DOUBLE_COLON",
		"QUESTION_MARK",
		"TILDE",
		"BIT_NOT_ASSIGN",
		"EXCLAMATION_MARK",
		"RIGHT_SHIFT",
		"RIGHT_SHIFT_ASSIGN",
		"LEFT_SHIFT",
		"LEFT_SHIFT_ASSIGN",

		"BRACKET_L",
		"BRACKET_R",
		"PAREN_L",
		"PAREN_R",
		"BRACE_L",
		"BRACE_R",

		"IF",
		"ELSE",
		"WHILE",
		"FOR",
		"CONTINUE",
		"BREAK",
		"RETURN",
		"SWITCH",
		"CASE",
		"FN",
		"INLINE",
		"VOID",
		"NAMESPACE",
		"CLASS",
		"STRUCT",
		"RAWTYPE",
		"UNION",
		"PUBLIC",
		"PROTECTED",
		"PRIVATE",
		"ASM",
		"STATIC",
		"DYNAMIC",
		"VIRTUAL",
		"CONST",
		"VOLATILE",
		"ISOLATED",
		"THIS"
	};

	return names[type];
};